### PR TITLE
feat: created datapoint, cluster classes, added create_clusters function

### PR DESCRIPTION
**Pull request by adityapentyala**
1. Created classes for datapoint, cluster objects for easy access to attributes such as paths, encodings
2. Created function create_clusters that returns a list of new clusters given an array of datapoints

### CODE REVIEW

**Review by majimearun — CHANGES_REQUESTED** [review]
1. Use a common formatting across files. We're currently using [google's style guide](https://google.github.io/styleguide/pyguide.html), so switch to that.
2. Complete your to do.
3. Add documentation and links to 3rd part libs as and when required.

**Comment by majimearun** [comment]
Take your time though, good start

**Comment by adityapentyala** [comment]
Update:
- Added docs

Yet to complete:
- Common formatting

**Review by majimearun — APPROVED** [review]
LGTM

**Pull request merged**
