### PR TITLE
Ml model rewrite

### PR DESCRIPTION
**Pull request by adityapentyala**
-   **Please check if the PR fulfills these requirements**

*   [x] The commit message follows our guidelines
*   [x] Tests for the changes have been added (for bug fixes / features)
*   [ ] Docs have been added / updated (for bug fixes / features)
*   [x] The code runs on the contributors machine.
*   [x] The code follows the code style guide of this project.

-   **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
   Feature: created FaceNet class that can return embeddings for given embedding size. Provides methods to save and load the model.

-   **What is the current behavior?** (You can also link to an open issue here)

-   **What is the new behavior (if this is a feature change)?**

-   **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

-   **Other information**:
 All written methods tested and work as expected. Tasks yet to complete:
 1. Will need to add method to train the model
 2. Docs for written code yet to be added

### CODE REVIEW

**Comment by majimearun** [comment]
Will merge after train method has been implemented, continue working on this branch till then. Also even if docs aren't added in this branch, do add example run details in a markdown file, so I know what I'm expecting this model to be doing when I'm testing it.

**Review by majimearun — CHANGES_REQUESTED** [review]
Will merge after train method has been implemented, continue working on this branch till then. Also even if docs aren't added in this branch, do add example run details in a markdown file, so I know what I'm expecting this model to be doing when I'm testing it.

**Comment by adityapentyala** [comment]
Added train method and tested in the notebook. Should i add the TripletDataset class defined in the notebook to the model.py file?

**Review by majimearun — APPROVED** [review]
LGTM

**Pull request merged**
